CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cpf VARCHAR(255),
    data_nascimento DATE,
    email VARCHAR(255),
    nome VARCHAR(255),
    senha VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE lancamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    data DATE,
    descricao VARCHAR(255),
    tipo VARCHAR(255) CHECK (tipo IN ('RECEITA', 'DESPESA')),
    valor DOUBLE PRECISION,
    usuario_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);